### PR TITLE
Add Docusaurus experiment

### PR DESCRIPTION
**Pull request by benjamin-thomas**
Hi Petter,

[This project](https://docusaurus.io/docs) came under radar lately. I thought it would be a good tool to make the presentation a bit nicer. The idea is to only use mardown files to reduce maintenance, and get some eye candy for free.

In short, to make that happen, there's a bunch of files surrounding the `./study` folder now . We can keep working on that folder as before though, nothing changes workflow-wise.

I've deployed a test to my [github pages](https://benjamin-thomas.github.io/caqti-study/study) if you want to have a look.

For info, there's a blog component that can be easily activated. If you ever wanted to create a post in tandem with a release, it'd be very easy, you'd only have to write a markdown file.

### CODE REVIEW

**Comment by paurkedal** [comment]
I haven't looked into the details, but I think the rendering looks very nice.  So, I guess this would be set up as a CI job?  And contributors would not need to install extra tools?

For blogging, I think it may be best to stick to discuss.ocaml.org.

**Comment by benjamin-thomas** [comment]
Great. Right now I can run a little script which updates the site via the github-pages mechanism. It takes a few seconds and I'm not sure it'd be that useful to automate yet.

If you don't know, by pushing to a special [gh-branch](https://github.com/benjamin-thomas/caqti-study/tree/gh-pages) as seen here in my fork, you get hosting for free, under your github username.

So the doc site could be hosted at: https://paurkedal.github.io/caqti-study. I'm not 100% sure if I could deploy as-is due to possible permission issues but i I could try if you think that sounds good.

A contributor could run the site locally via `npm`, but it wouldn't be a requirement. I can make a few tweaks here and there as needed. The main value comes from the markdown files which should be understandable as they are, without further tooling.

**Comment by paurkedal** [comment]
I have some concerns about breaking the premise of the current organization and style.  I think the current idea is that people should check out the repository and experiment with it.  Using the GitHub interface to browse it in parallel feels natural, as least for any seasoned developer.  If we switch the rendering, we loose the file-manager like functionality, unless the system we set up replicate it or provides an alternative.  In particular, I think it should be possible to browse the source files and see the layout.  I presume rendering the source code is supported, though we may have to add the layout and references to the files in the README or make a custom solution.

Is there a reason to pick this system over the many other solutions available?  I have used, or helped others use, solutions from make & XML & XSLT in the 2000s, to Jekyll & GitLab pages more recently, and for internal technical documentation we often use make & pandoc & graphviz & misc conversion tools.  On the other hand, given that this is an OCaml tutorial, I think it would also be motivational to use an OCaml-based solution if one of the currently active projects fits the bill.  I made a quick `opam search static site` and at least the following projects seems actively maintained:

  - [camyll](https://alan-j-hu.github.io/camyll/docs/index.html)
  - [soupalt](https://soupault.app/)
  - [stog](https://www.good-eris.net/stog/)
  - [yocaml](https://github.com/xhtmlboi/yocaml)

I think a reasonable alternative would be to use odoc, even if it's not markdown, since odoc can generate static sites featuring more than just APIs.  There is [a pull request](https://github.com/ocaml-doc/odoc-parser/pull/15) for markdown support in odoc, though [as pointed out](https://github.com/ocaml-doc/odoc-parser/blob/a7abb2193903bc68beeb1716228a684da6af2d05/doc/ocamlmark.md) the advantages are not clear-cut.

If we take this path, I think we should make clear what we want to achieve and consider options.

**Comment by paurkedal** [comment]
I experimented a bit with odoc and md2mld.  The latter allows writing documentation for odoc in markdown, but some work would be needed to get links correctly and render mermaid diagrams.  However, my conclusion is there are some limitations which makes it not the right tool here:

  - I didn't find a way to render source files as part of the tutorial, and external references may not be ideal.
  - The navigation and sidebar is based on packages, library, and modules.  We could utilise this by making each chapter a separate package, but it seems artificial.

On the good side, odoc allows us to render the doc-comments of the libraries.  It would be good to combine the best of both worlds, though I don't see a straight forward solution.

You mentioned gh-pages; I used that for the [Caqti API documentation](https://paurkedal.github.io/ocaml-caqti/index.html/), which I last time published with `dune-release` after having used custom scripts.  Since a few years back there has been a nicer rendering under https://ocaml.org/packages, though.  And apropos the sidebar, you can see here that the there are items for language-level objects, but not for [an auxiliary page](https://ocaml.org/p/caqti/latest/doc/query_template.html).

**Comment by benjamin-thomas** [comment]
> Is there a reason to pick this system over the many other solutions available?

I saw [this post](https://discuss.ocaml.org/t/using-docusaurus-to-document-an-ocaml-project/13359) on the OCaml forum a while ago and wondered for a while if this document generator could be a good fit for caqti-study.

If you don't feel that it's a good fit though, no worries. I'll close this PR for now and create an issue to re-explore the subject a bit later, after I've added more content.

> You mentioned gh-pages; I used that for the [Caqti API documentation](https://paurkedal.github.io/ocaml-caqti/index.html/), which I last time published with dune-release after having used custom scripts

Good to know, I missed that :+1:

**Pull request closed without merging**
